-- Running Training Plans Schema

-- User fitness tests to track current performance
CREATE TABLE IF NOT EXISTS user_fitness_tests (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  test_date DATE NOT NULL,
  test_distance DECIMAL(5,2) NOT NULL, -- in km (e.g., 5.0, 10.0, 21.1, 42.2)
  test_time INTERVAL NOT NULL, -- finish time (e.g., '00:25:30')
  estimated_vdot DECIMAL(5,2), -- Jack Daniels VDOT score
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Training plans for goal races
CREATE TABLE IF NOT EXISTS training_plans (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plan_name VARCHAR(255) NOT NULL,
  goal_race_distance DECIMAL(5,2) NOT NULL, -- in km
  goal_race_date DATE NOT NULL,
  goal_time INTERVAL, -- target finish time
  current_vdot DECIMAL(5,2) NOT NULL,
  plan_start_date DATE NOT NULL,
  plan_end_date DATE NOT NULL,
  training_days_per_week INTEGER NOT NULL CHECK (training_days_per_week BETWEEN 3 AND 7),
  current_weekly_mileage DECIMAL(5,2), -- starting mileage in km
  target_weekly_mileage DECIMAL(5,2), -- peak mileage in km
  status VARCHAR(50) DEFAULT 'active', -- active, completed, paused
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Daily workouts generated by the algorithm
CREATE TABLE IF NOT EXISTS planned_workouts (
  id SERIAL PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES training_plans(id) ON DELETE CASCADE,
  workout_date DATE NOT NULL,
  week_number INTEGER NOT NULL, -- which week of the plan
  workout_type VARCHAR(50) NOT NULL, -- easy, tempo, intervals, long_run, recovery, rest
  distance DECIMAL(5,2), -- total distance in km
  target_pace INTERVAL, -- per km (e.g., '00:05:30')
  warmup_distance DECIMAL(5,2),
  cooldown_distance DECIMAL(5,2),
  intervals_json JSONB, -- for interval workouts: {repeats: 6, distance: 0.8, pace: '00:04:00', recovery: 0.4}
  description TEXT, -- workout description
  completed BOOLEAN DEFAULT false,
  actual_distance DECIMAL(5,2), -- recorded after completion
  actual_duration INTERVAL, -- recorded after completion
  actual_pace INTERVAL, -- recorded after completion
  perceived_effort INTEGER CHECK (perceived_effort BETWEEN 1 AND 10), -- RPE 1-10
  notes TEXT, -- post-workout notes
  completed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(plan_id, workout_date)
);

-- Training zones calculated from VDOT
CREATE TABLE IF NOT EXISTS training_zones (
  id SERIAL PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES training_plans(id) ON DELETE CASCADE,
  zone_name VARCHAR(50) NOT NULL, -- easy, tempo, threshold, interval, repetition
  pace_per_km INTERVAL NOT NULL,
  heart_rate_min INTEGER,
  heart_rate_max INTEGER,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_fitness_tests_user ON user_fitness_tests(user_id, test_date DESC);
CREATE INDEX IF NOT EXISTS idx_training_plans_user ON training_plans(user_id, status);
CREATE INDEX IF NOT EXISTS idx_planned_workouts_plan ON planned_workouts(plan_id, workout_date);
CREATE INDEX IF NOT EXISTS idx_planned_workouts_date ON planned_workouts(workout_date);
CREATE INDEX IF NOT EXISTS idx_training_zones_plan ON training_zones(plan_id);

-- Sample data: Add a fitness test for user 1
INSERT INTO user_fitness_tests (user_id, test_date, test_distance, test_time, estimated_vdot, notes)
VALUES (1, CURRENT_DATE - INTERVAL '7 days', 5.0, '00:25:00', 42.5, 'Parkrun time trial')
ON CONFLICT DO NOTHING;
